version: '3.3'

services:
web:
    build: .
    ports:
      - "8080:8080"
  mysql:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: barbar
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"
#   web:
#     container_name: 'web'
#     build: .
#     volumes:
#       - .:/app
#       - node_modules:/app/node_modules
#     depends_on:
#       - db
#     ports:
#       - "7779:7779"
#     stdin_open: true
#     environment:
#       - PORT=7779
#     command: npm start 

#   db:
#     container_name: mariadb
#     image: mariadb
#     restart: always
#     environment:
#       MARIADB_ROOT_PASSWORD: 123456

#   adminer:
#     container_name: adminer
#     image: adminer
#     restart: always
#     ports:
#       - "3306:3306"

# volumes:
#   - node_modules