version: '3.3'

services:
  app:
    container_name: 'app'
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 7779:7779
    stdin_open: true
    environment:
      - PORT=7779
    command: npm start
volumes:
  node_modules: