version: '3.3'

services:
  web:
    container_name: 'web'
    build: .
    volumes:
      - .:/app
      # - node_modules:/app/node_modules
    depends_on:
      - db
    ports:
      - "7779:7779"
    stdin_open: true
    environment:
      - PORT=7779
    command: npm install && npm start 

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123456

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "3306:3306"