version: '3.3'

services:
  app:
    container_name: 'app'
    image: node:22
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 7779:7779
    stdin_open: true
    environment:
      - PORT=7779
      - NODE_ENV=production
    command: npm start

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 3306:3306
volumes:
  node_modules: