version: '3.3'

services:
  web:
    container_name: 'app'
    build: .
    volumes:
      - .:/app
      # - node_modules:/app/node_modules
    depends_on:
      - db
    ports:
      - 7779:7779
    stdin_open: true
    environment:
      - PORT=7779
    command: npm start 
